task:
  windows_container:
    image: cirrusci/windowsservercore:2016
  env:
    CIRRUS_SHELL: powershell
  test_script:
    - $test = "wer"
    - echo $test
    - foreach ($var in $env) {
        New-Variable -Name "$($var)" -Value "test" -Force
      }
    - echo $CIRRUS_SHELL
